# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/google-container-engine/#selecting-a-base-image
      - image: google/cloud-sdk

    environment:
      # https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/168#issuecomment-294418422
      - APPLICATION_ID: dev~brid-gy

    steps:
      - checkout

      - restore_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Base dependencies
          command: |
            apt-get update
            apt-get install -y python3

      - run:
          name: Python 3 dependencies
          command: |
            apt-get install -y python3-venv python3-dev
            python3 -m venv local3
            . local3/bin/activate
            pip install -U -r requirements.txt
            pip install mox3
            pip install coverage coveralls

      - run:
          name: Test Python 3
          command: |
            . local3/bin/activate
            CLOUDSDK_CORE_PROJECT=brid-gy gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 < /dev/null >& /dev/null &
            sleep 5s
            python -m coverage run --source=. --omit=admin.py,appengine_config.py,local3/\*,logs.py,scripts/\*,tests/\* -m unittest discover -v
            PYTHONPATH=. python tests/twitter_live_test.py --debug
            python -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then coveralls || true; fi

      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "local"

      - store_artifacts:
          path: /tmp/coverage_html
